spring.datasource.url=jdbc:postgresql://localhost:5432/elearning
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=localhost
spring.data.redis.port=6379

email.jobs.main.queue=gii-local-email-jobs-queue
spring.cloud.aws.sqs.listener.auto-startup=false