spring.datasource.url=jdbc:postgresql://localhost:5432/elearning
spring.datasource.username=postgres
spring.datasource.password=<REPLACE_WITH_YOUR_PASSWORD>

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=<REPLACE_WITH_YOUR_PASSWORD>

# SQS
email.jobs.main.queue=gii-local-email-jobs-queue
sms.jobs.main.queue=gii-local-sms-jobs-queue

# SMS
sms.provider.bulksmsbd.base-url=<SMS_PROVIDER_BULKSMSBD_BASE_URL>
sms.provider.bulksmsbd.api-key=<SMS_PROVIDER_BULKSMSBD_API_KEY>
sms.provider.bulksmsbd.sender-id=<SMS_PROVIDER_BULKSMSBD_SENDER_ID>

# SQS
aws.ses.access-key-id=<AWS_ACCESS_KEY_ID>
aws.ses.secret-access-key=<AWS_SECRET_ACCESS_KEY>
