spring.application.name=worker
spring.main.web-application-type=none

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.data.valkey.host=${SPRING_DATA_VALKEY_HOST}
spring.data.valkey.port=${SPRING_DATA_VALKEY_PORT}
spring.data.valkey.password=${SPRING_DATA_VALKEY_PASSWORD}

