# SQS
email.jobs.main.queue=gii-prod-email-jobs-queue
sms.jobs.main.queue=gii-prod-sms-jobs-queue
payments.sslcommerz.validation.jobs.queue=gii-prod-sslcommerz-validation-queue

# SMS
sms.provider.bulksmsbd.base-url=
