# SQS
email.jobs.main.queue=gii-stage-email-jobs-queue
sms.jobs.main.queue=gii-stage-sms-jobs-queue
payments.sslcommerz.validation.jobs.queue=gii-stage-sslcommerz-validation-queue

# SMS
sms.provider.bulksmsbd.base-url=http://bulksmsbd.net

# SSLCOMMERZ
payments.sslcommerz.validation-api-url=https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php