server.ssl.enabled=false

# JWT
app.jwt.secret=BASE64_SECRET

# POSTGRES DB
spring.datasource.url=jdbc:postgresql://localhost:5432/elearning
spring.datasource.username=postgres
spring.datasource.password=<REPLACE_WITH_YOUR_PASSWORD>
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=false

# VALKEY CACHE
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=<REPLACE_WITH_YOUR_PASSWORD>

# SQS
email.jobs.main.queue=gii-local-email-jobs-queue
sms.jobs.main.queue=gii-local-sms-jobs-queue
payments.sslcommerz.validation.jobs.queue=gii-local-sslcommerz-validation-queue

# SSLCommerz integration
payments.frontend-base-url=http://localhost:3000/payment/result
payments.callback-base-url=<base-url-for-payment-callbacks>
payments.sslcommerz.session-api-url=<SSL_COMMERZ_SESSION_API_URL>
payments.sslcommerz.validation-api-url=<SSL_COMMERZ_VALIDATION_API_URL>
payments.sslcommerz.store-id=<PAYMENTS_SSLCOMMERZ_STORE_ID>
payments.sslcommerz.store-password=test-password

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration,\
io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
spring.jpa.hibernate.ddl-auto=none
spring.data.jpa.repositories.enabled=false

# SMS
sms.provider.bulksmsbd.base-url=<SMS_PROVIDER_BULKSMSBD_BASE_URL>
sms.provider.bulksmsbd.api-key=<SMS_PROVIDER_BULKSMSBD_API_KEY>
sms.provider.bulksmsbd.sender-id=<SMS_PROVIDER_BULKSMSBD_SENDER_ID>

# SQS
aws.ses.access-key-id=<AWS_ACCESS_KEY_ID>
aws.ses.secret-access-key=<AWS_SECRET_ACCESS_KEY>