package com.gii.common.enums;

public enum PaymentEventType {
  CALLBACK_SUCCESS_REDIRECT,
  CALLBACK_SUCCESS,
  CALLBACK_FAILED,
  CALLBACK_CANCELLED,
  WEBHOOK_SUCCESS,
  SSLCOMMERZ_WEBHOOK,
  SSLCOMMERZ_WEBHOOK_RISK_HOLD,
  BKASH_WEBHOOK,
  BKASH_WEBHOOK_SNS
}
