spring.datasource.url=jdbc:postgresql://localhost:5432/elearning
spring.datasource.username=postgres
spring.datasource.password=<REPLACE_WITH_YOUR_PASSWORD>

# DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.ssl.enabled=false

email.jobs.main.queue=gii-local-email-jobs-queue
email.jobs.publish-timeout-ms=5000
sms.jobs.main.queue=gii-local-sms-jobs-queue
sms.jobs.publish-timeout-ms=5000

# JWT
app.jwt.secret=BASE64_SECRET
app.jwt.access-token-expiration-ms=900000

# Mux
mux.signing-key-id=
mux.private-key-pem=
mux.playback-token-ttl-s=900

# Bunny
bunny.token-security-key=
bunny.playback-token-ttl-s=900

# SSLCommerz
payments.sslcommerz.validation-base-url=https://sandbox.sslcommerz.com
payments.sslcommerz.validation-timeout-ms=10000
payments.sslcommerz.store-id=test-store
payments.sslcommerz.store-password=test-password

# bKash
payments.bkash.base-url=https://checkout.sandbox.bka.sh/v1.2.0-beta
payments.bkash.username=test-username
payments.bkash.password=test-password
payments.bkash.app-key=test-app-key
payments.bkash.app-secret=test-app-secret
payments.bkash.intent=sale
payments.bkash.timeout-ms=10000
