server.address=127.0.0.1

# SQS
email.jobs.main.queue=gii-stage-email-jobs-queue
sms.jobs.main.queue=gii-stage-sms-jobs-queue

# SSLCOMMERZ
payments.callback-base-url=https://stage-api.globalislamicinstitute.com
payments.sslcommerz.session-api-url=https://sandbox.sslcommerz.com/gwprocess/v4/api.php
payments.sslcommerz.validation-api-url=https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php

# BKASH
payments.bkash.base-url=https://checkout.sandbox.bka.sh/v1.2.0-beta
redirect.subdomain=stage-api

# CORS
app.cors.allowed-origin-patterns=*

# CLOUDFLARE R2
assets.base-url=https://stage-assets.globalislamicinstitute.com