spring.application.name=api
server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.data.valkey.host=${SPRING_DATA_VALKEY_HOST}
spring.data.valkey.port=${SPRING_DATA_VALKEY_PORT}
spring.data.valkey.password=${SPRING_DATA_VALKEY_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration