email.jobs.main.queue=gii-prod-email-jobs-queue
sms.jobs.main.queue=gii-prod-sms-jobs-queue
payments.sslcommerz.validation.jobs.queue=gii-prod-sslcommerz-validation-queue

payments.frontend-base-url=https://globalislamicinstitute.com/payment/result

# CORS
app.cors.allowed-origins=https://globalislamicinstitute.com,https://www.globalislamicinstitute.com,https://stage.globalislamicinstitute.com

# CLOUDFLARE R2
assets.base-url=https://assets.globalislamicinstitute.com
