spring.profiles.active=local

spring.application.name=api
server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# POSTGRES DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# VALKEY CACHE
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

spring.flyway.enabled=false

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true

# General API documentation
springdoc.api-docs.title=Global Islamic Institute Backend API
springdoc.api-docs.description=Comprehensive LMS for online course delivery
springdoc.api-docs.version=OPENAPI_3_1
springdoc.api-docs.contact.name=Rajib Alam
springdoc.api-docs.contact.email=rajibalam202@gmail.com
springdoc.api-docs.contact.url=

# MUX
mux.signing-key-id=${MUX_SIGNING_KEY_ID}
mux.private-key-prem=${MUX_SIGNING_SECRET_KEY}
mux.playback-token-ttl-s=${MUX_TOKEN_TTL}

# BUNNY
bunny.token-security-key=${BUNNY_API_KEY}
bunny.playback-token-ttl-s=${BUNNY_TOKEN_TTL}