spring.datasource.url=jdbc:postgresql://localhost:5432/elearning
spring.datasource.username=postgres
spring.datasource.password=postgres

# DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.ssl.enabled=false

email.jobs.main.queue=gii-local-email-jobs-queue

# JWT
app.jwt.secret=BASE64_SECRET
app.jwt.access-token-expiration-ms=900000

# Mux
mux.signing-key-id=
mux.private-key-prem=
mux.playback-token-ttl-s=900

# Bunny
bunny.token-security-key=
bunny.playback-token-ttl-s=900